- name: Create App Application Machine
  hosts: localhost
  environment:
    GCP_AUTH_KIND: "{{gcp_auth_kind}}"
    GCP_SERVICE_ACCOUNT_FILE: "{{ gcp_service_account_file }}"
    GCP_SCOPES: "{{gcp_scopes}}"

  tasks:
    # Create Compute Instance
    - name: Create instance
      gcp_compute_instance:
        name: "{{ machine_instance_name }}"
        machine_type: "{{ machine_type }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
                source_image: "projects/debian-cloud/global/images/family/debian-10"
                disk_size_gb: "{{ machine_disk_size }}"
        network_interfaces:
          - access_configs:
              - name: "External NAT"
                type: "ONE_TO_ONE_NAT"
        tags:
          items:
            - http-server
            - https-server
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        state: present
      register: instance